spring.application.name=Nexora

spring.datasource.url=jdbc:mysql://localhost:3306/nexora
spring.datasource.username=root
spring.datasource.password=Vaishnavi@11

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

logging.level.org.springframework.security=DEBUG